#
# FOLDER STRUCTURE
DATA_DIRECTORY = './data/'
UPLOAD_FOLDER = './uploads/'
EXTRACTED_PURCHASE_ORDERS_FOLDER = UPLOAD_FOLDER + 'purchase_orders/'
# PARSED_PURCHASED_ORDERS_FOLDER = DATA_DIRECTORY + 'purchase_orders/'

#
# MISCELLANEOUS FILES
KEYWORDS_FILE = DATA_DIRECTORY + "keywords.json"
PURCHASE_ORDERS_JSON = DATA_DIRECTORY + "updated_purchase_orders.json"
MATCHES_OUTPUT_FILES = DATA_DIRECTORY + "updated_matches.json"


#
# CLOUD OCR CONFIGURATIONS
SERVER_URL = "https://cloud.ocrsdk.com"
APPLICATION_ID = "1d28cdeb-ebda-478e-b614-57894acb992a"
PASSWORD = "KPbPS2UQfepxML4NnjDpUZQ5"
